model_params:
  name: 'ConvoVAE'
  in_channels: 1
  latent_dim: 12
  in_size: &m 17
  out_size: &n 34
  time_window: &tw 12

data_params:
  data_path: "/data/hinguyen/smpl_dataset/DIP_IMU_and_Others/"
  train_batch_size: 128
  val_batch_size:  128
  patch_size: 4
  num_workers: 4
  conv_data: &cv True
  time_window: *tw

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265
  m_measurement: *m
  n_input: *n
  time_window: *tw
  conv_data: *cv

trainer_params: &trainer_params
  gpus: [0]
  max_epochs: 101

logging_params:
  save_dir: "logs/"
  name: "ConvoVAE"
