model_params:
  name: 'ConvoVAE'
  in_channels: 1
  latent_dim: 20
  h_in: &h_in 120  # input's size should be a multiple of 12 (features)
  h_out: &h_out 204  # output's size = 17 * 3 * 3 + 17 * 3

data_params:
  data_path: "/data/hinguyen/smpl_dataset/DIP_IMU_and_Others/"
  train_batch_size: 120
  val_batch_size:  120
  patch_size: 4
  num_workers: 4

exp_params:
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.0005
  manual_seed: 1234
  h_in: *h_in
  h_out: *h_out

trainer_params: &trainer_params
  gpus: [0]
  max_epochs: 81

logging_params:
  save_dir: "/home/hinguyen/Data/PycharmProjects/compressive-sensing-imu/logs"
  name: "ConvoVAE"
