model_params:
  name: 'DIPVAE'
  latent_dim: 10
  h_in: &h_in 120  # compress 24 - 48 - 72 - 120* - 144 - 168 - 192
  h_out: &h_out 204
  eta: &eta 0.01  # CSNR(dB) 0 -> 30: 0.1 - 0.0562 - 0.0316 - 0.0178 - 0.01* - 0.0056 - 0.0031
  P_T: &P_T 0.01

data_params:
  data_path: "/data/hinguyen/smpl_dataset/DIP_IMU_and_Others/"
  train_batch_size: 60
  val_batch_size:  512
  patch_size: 4
  num_workers: 4


exp_params:
  LR: 0.00001
  weight_decay: 0
  scheduler_gamma: 0.95
  kld_weight: 0.00001
  manual_seed: 1234
  h_in: *h_in
  h_out: *h_out
  P_T: *P_T
  eta: *eta

trainer_params:
  gpus: [0]
  max_epochs: 51

logging_params:
  save_dir: "logs/"
  name: "DIPVAE"