model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 20
  hidden_dims: [4, 16, 64, 256, 512]

# "/data/hinguyen/smpl_dataset/DIP_IMU_and_Others/"
# "~/Data/"
data_params:
  data_path: "/data/hinguyen/smpl_dataset/DIP_IMU_and_Others/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 4
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 10

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"