model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 20
  hidden_dims: [64, 256, 512]
  in_size: 30
  out_size: 51

# "/data/hinguyen/smpl_dataset/DIP_IMU_and_Others/"
# "~/Data/"
data_params:
  data_path: "/data/hinguyen/smpl_dataset/DIP_IMU_and_Others/"
  train_batch_size: 128
  val_batch_size:  128
  patch_size: 4
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265
  m_measurement: 30
  n_input: 51
  time_window: 6

trainer_params:
  gpus: [0]
  max_epochs: 101

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"